// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/muxi-Infra/autossl-qiniuyun/controller"
	"github.com/muxi-Infra/autossl-qiniuyun/cron"
	"github.com/muxi-Infra/autossl-qiniuyun/router"
	"github.com/muxi-Infra/autossl-qiniuyun/service"
)

// Injectors from wire.go:

func InitApp() *App {
	qiniuSSL := cron.NewQiniuSSL()
	corn := cron.NewCorn(qiniuSSL)
	serviceService := service.NewService()
	engine := router.InitRouter(serviceService)
	app := NewApp(corn, engine)
	return app
}

// wire.go:

// wireSet 定义所有依赖
var wireSet = wire.NewSet(service.NewService, controller.NewController, cron.NewQiniuSSL, cron.NewCorn, router.InitRouter, NewApp)
