definitions:
  request.PUTConfReq:
    properties:
      conf:
        description: '"yaml配置"'
        type: string
    type: object
  response.GetConfResp:
    properties:
      conf:
        type: string
    type: object
  response.Resp:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /config/yaml:
    get:
      consumes:
      - application/json
      description: 返回整个 YAML 配置文件内容
      produces:
      - application/json
      responses:
        "200":
          description: 返回 YAML 格式的配置内容
          schema:
            $ref: '#/definitions/response.Resp'
        "500":
          description: 服务器错误
          schema:
            allOf:
            - $ref: '#/definitions/response.Resp'
            - properties:
                data:
                  $ref: '#/definitions/response.GetConfResp'
              type: object
      summary: 获取当前 YAML 配置
      tags:
      - 配置管理
    put:
      consumes:
      - application/json
      description: 接收 JSON 格式的 YAML 配置内容并覆盖当前配置
      parameters:
      - description: 更新配置
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/request.PUTConfReq'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            $ref: '#/definitions/response.Resp'
        "400":
          description: 请求格式错误
          schema:
            $ref: '#/definitions/response.Resp'
        "500":
          description: 服务器错误
          schema:
            $ref: '#/definitions/response.Resp'
      summary: 更新 YAML 配置
      tags:
      - 配置管理
swagger: "2.0"
